language: scala
sudo: false
jdk:
  - oraclejdk8
script:
  - sbt +test

cache:
  directories:
    - $HOME/.ivy2/cache
before_cache:
  # Ensure changes to the cache aren't persisted
  - rm -rf $HOME/.ivy2/cache/com.example
  # Delete all ivydata files since ivy touches them on each build
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  bucket: online-auction-bucket
  region: us-east-2

- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: online-auction-bucket
  key: latest.zip
  bundle_type: zip
  application: online-auction-scala
  deployment_group: deploymentGroup
  region: us-east-2



script:
  - sbt dist
  -  zip -r latest . -i *.zip appspec.yml
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip

notifications:
 email: vinay.bhagwat@afourtech.com

