version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Project


hooks:
  AfterInstall:
    - location: deployment-scripts/after-install/UnzipResourceBundle.sh
      timeout: 1800
      runas: root

  BeforeInstall:
  - location:  deployment-scripts/before-install/Stop_server.sh
    timeout: 180
    runas: root