version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Deployment_Env

hooks:
  AfterInstall:
    - location: deployment-scripts/after-install/UnzipResourceBundle.sh
      timeout: 180
      runas: root

  BeforeInstall:
  - location:  deployment-scripts/before-install/Stop_server.sh