version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Project

hooks:
  AfterInstall:
    - location: deployment-scripts/after-install/UnzipResourceBundle.sh
      timeout: 180
      runas: root

